CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  entra_oid VARCHAR(64) NOT NULL,
  email VARCHAR(255) NULL,
  id_card_number VARCHAR(32) NULL,
  staff_id VARCHAR(64) NULL,
  full_name VARCHAR(255) NOT NULL,
  dob DATE NULL,
  department VARCHAR(128) NULL,
  job_title VARCHAR(128) NULL,
  join_date DATE NULL,
  photo_path VARCHAR(2048) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_entra_oid (entra_oid),
  UNIQUE KEY uk_users_staff_id (staff_id),
  UNIQUE KEY uk_users_id_card_number (id_card_number),
  KEY idx_users_deleted_at (deleted_at),
  KEY idx_users_department (department),
  KEY idx_users_email (email),
  KEY idx_users_full_name (full_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
